/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculatrice;

import org.junit.Test;

import static org.junit.Assert.*;

import org.mariuszgromada.math.mxparser.*;

public class AppTest {

    @Test
    public void calculateAlgebr(){
        String s = "10-4*5/2";
        int res = 10-4*5/2;
        Expression e1 = new Expression(s);
        assertEquals(res, e1.calculate(), 0.0);
    }



}